# roles/beanstalkd/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_beanstalkd_namespace }}"
    - "{{ openio_beanstalkd_sysconfig_dir }}/beanstalkd-{{ openio_beanstalkd_serviceid }}"
    - "{{ openio_beanstalkd_volume }}"
    - "/var/log/oio/sds/{{ openio_beanstalkd_namespace }}/beanstalkd-{{ openio_beanstalkd_serviceid }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "beanstalkd.conf.j2"
      dest: "{{ openio_beanstalkd_sysconfig_dir }}/\
        beanstalkd-{{ openio_beanstalkd_serviceid }}/beanstalkd-{{ openio_beanstalkd_serviceid }}.conf"
    - src: "gridinit_beanstalkd.conf.j2"
      dest: "{{ openio_beanstalkd_gridinit_dir }}/{{ openio_beanstalkd_gridinit_file_prefix }}\
        beanstalkd-{{ openio_beanstalkd_serviceid }}.conf"
  register: _beanstalkd_conf

- name: restart beanstalkd
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_beanstalkd_namespace}}-beanstalkd-{{openio_beanstalkd_serviceid}}
  when:
    - _beanstalkd_conf.changed
    - not openio_beanstalkd_provision_only
  tags: configure
...
