# roles/beanstalkd/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - install
    - configure

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_beanstalkd_namespace }}"
    - path: "{{ openio_beanstalkd_sysconfig_dir }}/{{ openio_beanstalkd_servicename }}"
    - path: "{{ openio_beanstalkd_volume }}"
    - path: "/etc/oio/sds/{{ openio_beanstalkd_namespace }}/watch"
    - path: "/var/log/oio/sds/{{ openio_beanstalkd_namespace }}/{{ openio_beanstalkd_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: configure

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "beanstalkd.conf.j2"
      dest: "{{ openio_beanstalkd_sysconfig_dir }}/\
        {{ openio_beanstalkd_servicename }}/{{ openio_beanstalkd_servicename }}.conf"
    - src: "gridinit_beanstalkd.conf.j2"
      dest: "{{ openio_beanstalkd_gridinit_dir }}/{{ openio_beanstalkd_gridinit_file_prefix }}\
        {{ openio_beanstalkd_servicename }}.conf"
    - src: "watch-beanstalkd.yml.j2"
      dest: "{{ openio_beanstalkd_sysconfig_dir }}/watch/{{ openio_beanstalkd_servicename }}.yml"
  register: _beanstalkd_conf
  tags: configure

- name: "restart beanstalkd to apply the new configuration"
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_beanstalkd_namespace }}-{{ openio_beanstalkd_servicename }}
  register: _restart_beanstalkd
  when:
    - _beanstalkd_conf is changed
    - not openio_beanstalkd_provision_only
  tags: configure

- block:
    - name: "Ensure beanstalkd is started"
      command: gridinit_cmd start {{ openio_beanstalkd_namespace }}-{{ openio_beanstalkd_servicename }}
      register: _start_beanstalkd
      changed_when: '"Success" in _start_beanstalkd.stdout'
      when:
        - not openio_beanstalkd_provision_only
        - _restart_beanstalkd is skipped
      tags: configure

    - name: check beanstalkd
      wait_for:
        host: "{{ openio_beanstalkd_bind_address }}"
        port: "{{ openio_beanstalkd_bind_port }}"
      register: _beanstalkd_check
      retries: 3
      delay: 5
      until: _beanstalkd_check is success
      changed_when: false
      tags: configure
      when:
        - not openio_beanstalkd_provision_only
  when: openio_bootstrap | d(false)
...
